# Generated by Django 5.0.6 on 2024-06-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('action', models.BooleanField(default=False)),
                ('adventure', models.BooleanField(default=False)),
                ('comedy', models.BooleanField(default=False)),
                ('drama', models.BooleanField(default=False)),
                ('horror', models.BooleanField(default=False)),
                ('fantasy', models.BooleanField(default=False)),
                ('sf', models.BooleanField(default=False)),
                ('romance', models.BooleanField(default=False)),
                ('thriller', models.BooleanField(default=False)),
                ('mystery', models.BooleanField(default=False)),
                ('animation', models.BooleanField(default=False)),
                ('documentary', models.BooleanField(default=False)),
                ('musical', models.BooleanField(default=False)),
                ('war', models.BooleanField(default=False)),
                ('western', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
