# Generated by Django 5.0.6 on 2024-06-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_movie_delete_answer_delete_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='action',
            field=models.BooleanField(default=True),
        ),
    ]
