# Generated by Django 5.0.6 on 2024-06-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_movie_likebool_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='ytburl',
            field=models.CharField(default='kamsx_g2hnI', max_length=200),
        ),
    ]
